### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by NoahStepheno** [liriliri/chobitsu#4]
I want to add source file, on source panel.

![image](https://user-images.githubusercontent.com/64339985/142981767-82a06858-6fc0-4a57-b1a2-61d14a1d4ab8.png)

And I implemenet Page.getResourceTree

like this. but it doesn't make sense.

![image](https://user-images.githubusercontent.com/64339985/142981870-1b66feba-d80c-4739-bade-29fd80e8c0ce.png)

I don't understand which feature shold be implemented.

**Comment by NoahStepheno** [comment]
Can not find target.js style.css

**Comment by surunzi** [comment]
Sources files are supported now, though you can only view file content if they can be fetched by xhr.
